# Generated by Django 5.0 on 2023-12-12 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='store_name',
            field=models.CharField(max_length=100),
        ),
    ]
